<?php
require_once __DIR__ . '/config.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: Thu, 01 Jan 1970 00:00:00 GMT');
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'customer') {
    header('Location: index.php');
    exit;
}
$name = $_SESSION['full_name'];
$theme = $_SESSION['display_theme'] ?? 'teal';
$gcashQrAsset = htmlspecialchars(getPaymentQrAsset(), ENT_QUOTES, 'UTF-8');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Paradise Resort - Customer Portal</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
<style>
  :root{--teal:#009688;--teal-dark:#00796B;--teal-light:#4DB6AC;--bg:#eef7f6;--text:#173636;--muted:#6e8686;--card:#fff;--shadow:0 20px 45px rgba(0,0,0,.10)}
  body[data-theme="sunset"]{--teal:#E76F51;--teal-dark:#D55A3C;--teal-light:#F4A261;--bg:#fff5f0}
  body[data-theme="ocean"]{--teal:#1E88E5;--teal-dark:#1565C0;--teal-light:#64B5F6;--bg:#eff7ff}
  *{box-sizing:border-box;margin:0;padding:0} body{font-family:'Lato',sans-serif;background:var(--bg);color:var(--text)}
  header{position:sticky;top:0;z-index:100;height:76px;padding:0 28px;background:linear-gradient(135deg,var(--teal-dark),var(--teal));display:flex;align-items:center;justify-content:space-between;color:#fff;box-shadow:0 12px 30px rgba(0,0,0,.15)}
  .brand h1{font-family:'Playfair Display',serif;font-size:2.2rem;line-height:1}.brand p{font-size:1.22rem;font-weight:700;opacity:.98;margin-top:6px}
  .actions{display:flex;align-items:center;gap:12px}.action-btn,.logout{border:none;border-radius:999px;padding:10px 16px;font-weight:700;cursor:pointer}
  .action-btn{background:rgba(255,255,255,.14);color:#fff;border:1px solid rgba(255,255,255,.32)} .logout{background:rgba(255,255,255,.14);color:#fff;border:1px solid rgba(255,255,255,.32)}
  .notify-wrap{position:relative}.notify-btn{position:relative;width:46px;height:46px;border-radius:50%;border:1px solid rgba(255,255,255,.32);background:rgba(255,255,255,.14);color:#fff;cursor:pointer}.notify-count{position:absolute;top:-4px;right:-1px;min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:#ff5252;color:#fff;font-size:.72rem;font-weight:700;display:none;align-items:center;justify-content:center}.notify-count.show{display:flex}
  .notify-panel{position:absolute;top:58px;right:0;width:350px;max-height:420px;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 50px rgba(0,0,0,.18);padding:14px;display:none;color:var(--text)}.notify-panel.active{display:block}.notify-panel h3{font-family:'Playfair Display',serif;font-size:1.08rem;color:var(--teal-dark);margin-bottom:4px}.notify-panel p{font-size:.8rem;color:var(--muted);margin-bottom:12px}
  .notify-item{background:#f8fbfb;border:1px solid #edf4f4;border-radius:14px;padding:12px;margin-bottom:10px}.notify-top{display:flex;justify-content:space-between;gap:10px;margin-bottom:6px}.notify-title{font-size:.88rem;font-weight:700}.notify-meta{font-size:.78rem;color:#6e7f7f;line-height:1.45}
  .status{display:inline-block;padding:4px 12px;border-radius:999px;font-size:.76rem;font-weight:700}.pending{background:#fff3cd;color:#8a6500}.confirmed{background:#e8f5e9;color:#2e7d32}.cancelled{background:#ffebee;color:#c62828}
  .top-tabs{max-width:1200px;margin:28px auto 0;padding:0 24px;display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap}.tabs{display:inline-flex;background:#fff;border-radius:999px;box-shadow:var(--shadow);overflow:hidden}.tab{border:none;background:none;padding:12px 28px;font-size:.94rem;font-weight:700;cursor:pointer;color:#768989}.tab.active{background:var(--teal);color:#fff}
  .browse-tools{display:flex;justify-content:flex-end;align-items:center;gap:12px;flex:0 0 auto}.search-wrap{width:min(360px,100%);position:relative}.search-wrap input{width:100%;padding:13px 18px;border:1.5px solid #d7e8e6;border-radius:999px;background:#fff;box-shadow:var(--shadow);font-size:.95rem;outline:none}.search-wrap input:focus{border-color:var(--teal-light)}
  .main{max-width:1200px;margin:0 auto;padding:22px 24px 60px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:24px}.card{background:#fff;border-radius:24px;overflow:hidden;box-shadow:var(--shadow);transition:transform .25s}.card:hover{transform:translateY(-8px)}.media{position:relative;height:220px}.media img{width:100%;height:100%;object-fit:cover}
  .hover{position:absolute;inset:0;padding:18px;background:linear-gradient(180deg,rgba(8,24,24,.08),rgba(8,24,24,.84));color:#fff;opacity:0;transition:opacity .25s;display:flex;flex-direction:column;justify-content:flex-end}.card:hover .hover{opacity:1}.hover p{font-size:.84rem;line-height:1.5;margin:8px 0 12px}.badges{display:flex;flex-wrap:wrap;gap:8px}.badges span{padding:6px 10px;border-radius:999px;background:rgba(255,255,255,.16);font-size:.74rem}
  .info{padding:18px 20px 20px}.info h3{font-family:'Playfair Display',serif;font-size:1.22rem;margin-bottom:8px}.info p{color:var(--muted);line-height:1.55;min-height:48px}.meta{display:flex;gap:12px;flex-wrap:wrap;font-size:.84rem;color:#5a7272;margin:12px 0}.pill{background:#e8f6f4;color:var(--teal-dark);padding:5px 10px;border-radius:999px;font-weight:700}
  .bottom{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:12px}.price{font-size:1.28rem;font-weight:700;color:var(--teal-dark)}.price small{font-size:.78rem;color:#889b9b}.book{background:var(--teal);color:#fff;border:none;border-radius:999px;padding:11px 18px;font-weight:700;cursor:pointer}
  .booking-card{background:#fff;border-radius:22px;overflow:hidden;box-shadow:var(--shadow);margin-bottom:20px}.booking-head{background:linear-gradient(135deg,rgba(0,121,107,.88),rgba(0,150,136,.82)),var(--booking-bg);background-size:cover;background-position:center;color:#fff;padding:16px 22px;display:flex;justify-content:space-between;align-items:flex-start;gap:18px}.booking-body{position:relative;padding:24px;display:flex;justify-content:space-between;gap:22px;flex-wrap:wrap;overflow:hidden}.booking-body::before{content:'';position:absolute;inset:0;background-image:var(--booking-bg);background-size:cover;background-position:center;filter:blur(5px);transform:scale(1.05);opacity:.58}.booking-body::after{content:'';position:absolute;inset:0;background:rgba(255,255,255,.46)}.booking-body>*{position:relative;z-index:1}
  .booking-list{display:grid;gap:12px}.booking-line{display:flex;gap:12px;align-items:flex-start}.booking-line strong{display:block;font-size:.8rem;color:#617777}.booking-line span{font-size:1rem;font-weight:700}.summary{min-width:260px;background:linear-gradient(135deg,#e2f6f4,#c2e8e4);border-radius:18px;padding:18px;text-align:center}.summary .big{font-size:1.8rem;font-weight:700;color:var(--teal-dark)}.summary .small{font-size:.8rem;color:#5e7676;line-height:1.55;margin-top:8px}
  .cancel-btn{margin-top:14px;width:100%;border:none;border-radius:999px;padding:11px;background:#f44336;color:#fff;font-weight:700;cursor:pointer}
  .empty{text-align:center;padding:56px 20px;color:#8aa0a0}
  .overlay{position:fixed;inset:0;background:rgba(8,22,22,.62);display:none;align-items:center;justify-content:center;z-index:200;padding:20px}.overlay.active{display:flex}
  .modal{width:min(100%,820px);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;box-shadow:0 24px 60px rgba(0,0,0,.22);padding:28px;position:relative}.modal.small{width:min(100%,560px)}.close{position:absolute;top:12px;right:16px;background:none;border:none;font-size:1.7rem;color:#9aa9a9;cursor:pointer}
  .modal h2{font-family:'Playfair Display',serif;font-size:1.65rem;color:var(--teal-dark);margin-bottom:6px}.sub{color:var(--muted);line-height:1.55;margin-bottom:18px}
  .form-grid{display:grid;gap:14px}.form-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.group label{display:block;font-size:.82rem;font-weight:700;color:#4e6666;margin-bottom:6px}.group input,.group select,.group textarea{width:100%;padding:12px 14px;border:1.5px solid #d8e8e7;border-radius:16px;background:#fbfefe;font-size:.94rem;outline:none}.group textarea{min-height:120px;resize:vertical}
  .booking-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.side{background:linear-gradient(180deg,rgba(0,150,136,.08),rgba(77,182,172,.03));border:1px solid rgba(0,150,136,.12);border-radius:22px;padding:18px}.box,.qr{background:#fff;border:1px solid #e7f1f0;border-radius:18px;padding:16px;margin-bottom:14px}.value{font-size:1.45rem;font-weight:700;color:var(--teal-dark)}.note{font-size:.82rem;color:#6d8484;line-height:1.6;margin-top:6px}.qr{text-align:center}.qr img{width:min(100%,260px);max-height:420px;height:auto;object-fit:contain;margin:0 auto 12px;display:block}
  .avail{display:inline-flex;padding:10px 14px;border-radius:999px;font-size:.82rem;font-weight:700;background:#edf8f7;color:var(--teal-dark);margin:6px 0 14px}.avail.available{background:#e8f5e9;color:#2e7d32}.avail.unavailable{background:#ffebee;color:#c62828}
  .actions-row{display:flex;justify-content:flex-end;gap:12px;margin-top:18px}.btn{border:none;border-radius:999px;padding:12px 18px;font-weight:700;cursor:pointer}.btn.secondary{background:#f2f6f6;color:#617777}.btn.primary{background:var(--teal);color:#fff}.btn.primary:disabled{background:#bad8d5;color:#f8ffff;cursor:not-allowed}
  .error,.success{display:none;margin-top:12px;font-size:.84rem;font-weight:700;text-align:center}.error{color:#c62828}.success{color:#2e7d32}
  @media(max-width:980px){.booking-layout,.form-grid.two{grid-template-columns:1fr}} @media(max-width:760px){header{padding:0 18px}.top-tabs,.main{padding-left:16px;padding-right:16px}.top-tabs{align-items:stretch}.actions{gap:8px}.action-btn,.logout{padding:10px 12px;font-size:.82rem}.browse-tools{justify-content:stretch;flex:1 1 100%}.search-wrap{width:100%}}
</style>
</head>
<body data-theme="<?= htmlspecialchars($theme) ?>">
<header>
  <div class="brand"><h1>Paradise Resort</h1><p>Welcome back, <span id="profile-name-display"><?= htmlspecialchars($name) ?></span></p></div>
  <div class="actions">
    <button class="action-btn" type="button" id="theme-button" onclick="cycleTheme()">Theme: <?= htmlspecialchars(ucfirst($theme)) ?></button>
    <button class="action-btn" type="button" onclick="openProfileModal()">Profile</button>
    <div class="notify-wrap">
      <button class="notify-btn" type="button" onclick="toggleNotifications()">&#128276;<span class="notify-count" id="notify-count">0</span></button>
      <div class="notify-panel" id="notify-panel"><h3>Booking Notifications</h3><p>Confirmed and cancelled updates appear here.</p><div id="notify-list"><div class="empty" style="padding:18px 10px">Loading notifications...</div></div></div>
    </div>
    <button class="logout" type="button" onclick="logout()">Logout</button>
  </div>
</header>
<div class="top-tabs"><div class="tabs"><button class="tab active" id="tab-browse" onclick="showTab('browse')">Browse Cottages</button><button class="tab" id="tab-bookings" onclick="showTab('bookings')">My Booking</button></div><div class="browse-tools"><div class="search-wrap"><input type="search" id="cottage-search" placeholder="Search cottages, type, amenities..."></div></div></div>
<main class="main">
  <div id="pane-browse"><div class="grid" id="cottages-grid"><div class="empty" style="grid-column:1/-1">Loading cottages...</div></div></div>
  <div id="pane-bookings" style="display:none"><div id="bookings-container" style="margin-top:24px"><div class="empty">Loading bookings...</div></div></div>
</main>

<div class="overlay" id="booking-modal"><div class="modal"><button class="close" type="button" onclick="closeBookingModal()">&times;</button><h2 id="booking-title">Book Cottage</h2><p class="sub">Choose your stay dates, times, number of guests, and review the down payment before confirming.</p><div class="booking-layout"><div><div class="form-grid two"><div class="group" style="grid-column:1/-1"><label>Cottage</label><input id="booking-cottage-name" type="text" readonly></div><div class="group"><label>Number of Guests</label><input type="number" min="1" id="booking-guest-count" value="1"></div><div class="group"><label>Capacity</label><input id="booking-capacity" type="text" readonly></div><div class="group"><label>Check-In Date</label><input type="date" id="checkin-date"></div><div class="group"><label>Check-In Time</label><input type="time" id="checkin-time" value="14:00"></div><div class="group"><label>Check-Out Date</label><input type="date" id="checkout-date"></div><div class="group"><label>Check-Out Time</label><input type="time" id="checkout-time" value="12:00"></div></div><div class="avail" id="availability-status">Select dates to check availability.</div><div class="error" id="book-error"></div><div class="success" id="book-success"></div><div class="actions-row"><button class="btn secondary" type="button" onclick="closeBookingModal()">Cancel</button><button class="btn primary" id="confirm-booking-btn" type="button" onclick="confirmBooking()">Confirm Booking</button></div></div><div class="side"><div class="box"><div style="font-size:.84rem;color:#6d8484;margin-bottom:6px">Total Amount</div><div class="value" id="booking-total">PHP 0</div><div class="note" id="booking-total-meta">Choose dates to compute the total.</div></div><div class="box"><div style="font-size:.84rem;color:#6d8484;margin-bottom:6px">Down Payment</div><div class="value" id="booking-down-payment">PHP 0</div><div class="note">A 30% down payment reference is saved with your booking.</div></div><div class="qr"><img src="<?= $gcashQrAsset ?>" alt="GCash QR"><strong style="display:block;color:var(--teal-dark);margin-bottom:6px">GCash QR</strong><div class="note">Use this QR reference for your down payment after submitting the booking.</div></div></div></div></div></div>

<div class="overlay" id="profile-modal"><div class="modal small"><button class="close" type="button" onclick="closeProfileModal()">&times;</button><h2>My Profile</h2><p class="sub">Update your name, phone, theme, and password from here.</p><div class="form-grid two"><div class="group"><label>Full Name</label><input type="text" id="profile-full-name"></div><div class="group"><label>Email</label><input type="email" id="profile-email" readonly></div><div class="group"><label>Phone Number</label><input type="text" id="profile-phone"></div><div class="group"><label>Theme</label><select id="profile-theme"><option value="teal">Teal</option><option value="sunset">Sunset</option><option value="ocean">Ocean</option></select></div></div><div class="form-grid two" style="margin-top:16px"><div class="group"><label>Current Password</label><input type="password" id="profile-current-password"></div><div class="group"><label>New Password</label><input type="password" id="profile-new-password"></div><div class="group" style="grid-column:1/-1"><label>Confirm New Password</label><input type="password" id="profile-confirm-password"></div></div><div class="error" id="profile-error"></div><div class="success" id="profile-success"></div><div class="actions-row"><button class="btn secondary" type="button" onclick="closeProfileModal()">Close</button><button class="btn primary" type="button" onclick="saveProfile()">Save Profile</button></div></div></div>

<script>
let cottages=[],currentCottage=null,bookings=[],selectedAvailable=false,profile=null,refreshTimer=null;
const today=(new Date()).toISOString().split('T')[0],themes=['teal','sunset','ocean'];
function showTab(tab){document.getElementById('pane-browse').style.display=tab==='browse'?'':'none';document.getElementById('pane-bookings').style.display=tab==='bookings'?'':'none';document.getElementById('tab-browse').classList.toggle('active',tab==='browse');document.getElementById('tab-bookings').classList.toggle('active',tab==='bookings');if(tab==='bookings')loadMyBookings()}
function money(v){return 'PHP '+Number(v||0).toLocaleString()}
function setTheme(theme){document.body.dataset.theme=theme;document.getElementById('profile-theme').value=theme;document.getElementById('theme-button').textContent='Theme: '+theme.charAt(0).toUpperCase()+theme.slice(1)}
function cycleTheme(){const current=document.body.dataset.theme||'teal';const next=themes[(themes.indexOf(current)+1)%themes.length];setTheme(next);if(profile){profile.display_theme=next}saveProfile(false)}
async function loadProfile(){try{const fd=new FormData();fd.append('action','profile');const res=await fetch('auth.php',{method:'POST',body:fd,cache:'no-store'});const data=await res.json();if(!data.success)return;profile=data.profile;document.getElementById('profile-full-name').value=profile.full_name||'';document.getElementById('profile-email').value=profile.email||'';document.getElementById('profile-phone').value=profile.phone||'';document.getElementById('profile-theme').value=profile.display_theme||'teal';document.getElementById('profile-name-display').textContent=profile.full_name||'';setTheme(profile.display_theme||'teal')}catch(e){console.error('Profile load failed',e)}}
function openProfileModal(){document.getElementById('profile-error').style.display='none';document.getElementById('profile-success').style.display='none';openModal('profile')}
function closeProfileModal(){closeModal('profile')}
async function saveProfile(showMessage=true){const err=document.getElementById('profile-error'),ok=document.getElementById('profile-success');err.style.display='none';ok.style.display='none';const fd=new FormData();fd.append('action','update_profile');fd.append('full_name',document.getElementById('profile-full-name').value);fd.append('phone',document.getElementById('profile-phone').value);fd.append('display_theme',document.getElementById('profile-theme').value);const res=await fetch('auth.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){if(showMessage){err.textContent=data.message||'Could not update profile.';err.style.display='block'}return false}profile={...(profile||{}),...data.profile,email:document.getElementById('profile-email').value};document.getElementById('profile-name-display').textContent=data.profile.full_name;setTheme(data.profile.display_theme);const current=document.getElementById('profile-current-password').value,newPass=document.getElementById('profile-new-password').value,confirm=document.getElementById('profile-confirm-password').value;if(current||newPass||confirm){const pw=new FormData();pw.append('action','change_password');pw.append('current_password',current);pw.append('new_password',newPass);pw.append('confirm_password',confirm);const pwRes=await fetch('auth.php',{method:'POST',body:pw});const pwData=await pwRes.json();if(!pwData.success){if(showMessage){err.textContent=pwData.message||'Could not change password.';err.style.display='block'}return false}document.getElementById('profile-current-password').value='';document.getElementById('profile-new-password').value='';document.getElementById('profile-confirm-password').value=''}if(showMessage){ok.textContent='Profile updated successfully.';ok.style.display='block'}return true}
function openModal(type){document.getElementById(type+'-modal').classList.add('active')}
function closeModal(type){document.getElementById(type+'-modal').classList.remove('active')}
function renderCottages(){const grid=document.getElementById('cottages-grid');const query=(document.getElementById('cottage-search')?.value||'').trim().toLowerCase();const filtered=cottages.filter(c=>{if(!query)return true;return [c.name,c.description,c.type,c.amenities,c.pricing_unit,String(c.capacity),String(c.price)].join(' ').toLowerCase().includes(query)});if(!filtered.length){grid.innerHTML=`<div class="empty" style="grid-column:1/-1">${query?'No cottages match your search.':'No cottages available.'}</div>`;return}grid.innerHTML=filtered.map(c=>{const amenities=(c.amenities||'').split(',').map(v=>v.trim()).filter(Boolean);return `<article class="card"><div class="media"><img src="${c.image_url}" alt="${c.name}" onerror="this.src='assets/cottages/paradise-nook-cottage.jpg'"><div class="hover"><h4>${c.name}</h4><p>${c.description||'A tropical stay designed for comfort and easy resort access.'}</p><div class="badges"><span>${c.type}</span><span>${c.capacity} guests</span>${amenities.slice(0,3).map(item=>`<span>${item}</span>`).join('')}</div></div></div><div class="info"><h3>${c.name}</h3><p>${c.description||'A tropical stay designed for comfort and easy resort access.'}</p><div class="meta"><span class="pill">${c.type}</span><span>Capacity: <strong>${c.capacity}</strong></span></div><div class="bottom"><div class="price">${money(c.price)} <small>/ ${c.pricing_unit}</small></div><button class="book" type="button" onclick="openBooking(${c.id})">Book Now</button></div></div></article>`}).join('')}
async function loadCottages(){const grid=document.getElementById('cottages-grid');try{const res=await fetch(`cottages.php?action=list&_=${Date.now()}`,{cache:'no-store'});const text=await res.text();const data=JSON.parse(text);cottages=data.success&&Array.isArray(data.cottages)?data.cottages:[];renderCottages()}catch(e){console.error('Cottage load failed',e);grid.innerHTML='<div class="empty" style="grid-column:1/-1">Could not load cottages.</div>'}}
function openBooking(cottageId){currentCottage=cottages.find(c=>Number(c.id)===Number(cottageId))||null;if(!currentCottage)return;document.getElementById('booking-title').textContent=currentCottage.name;document.getElementById('booking-cottage-name').value=currentCottage.name;document.getElementById('booking-capacity').value=currentCottage.capacity+' guests';document.getElementById('booking-guest-count').value='1';document.getElementById('checkin-date').value=today;const next=new Date();next.setDate(next.getDate()+1);const nextValue=next.toISOString().split('T')[0];document.getElementById('checkout-date').value=nextValue;document.getElementById('checkin-date').min=today;document.getElementById('checkout-date').min=nextValue;document.getElementById('checkin-time').value='14:00';document.getElementById('checkout-time').value='12:00';document.getElementById('book-error').style.display='none';document.getElementById('book-success').style.display='none';updateBookingSummary();checkAvailability();openModal('booking')}
function closeBookingModal(){closeModal('booking')}
function updateBookingSummary(){if(!currentCottage)return;const start=new Date(document.getElementById('checkin-date').value),end=new Date(document.getElementById('checkout-date').value);let units=Math.max(1,Math.round((end-start)/86400000));if(currentCottage.pricing_unit==='event')units=1;const total=Number(currentCottage.price)*units;document.getElementById('booking-total').textContent=money(total);document.getElementById('booking-down-payment').textContent=money(total*.3);document.getElementById('booking-total-meta').textContent=`${units} ${currentCottage.pricing_unit}${units===1?'':'s'} x ${money(currentCottage.price)} | Capacity ${currentCottage.capacity} guests`}
function setAvailability(ok,msg){const el=document.getElementById('availability-status'),btn=document.getElementById('confirm-booking-btn');selectedAvailable=ok;el.textContent=msg;el.className='avail '+(ok?'available':'unavailable');btn.disabled=!ok}
async function checkAvailability(){if(!currentCottage)return;const fd=new FormData();fd.append('action','availability');fd.append('cottage_id',currentCottage.id);fd.append('check_in',document.getElementById('checkin-date').value);fd.append('check_out',document.getElementById('checkout-date').value);fd.append('guest_count',document.getElementById('booking-guest-count').value);setAvailability(false,'Checking availability...');const res=await fetch('reservations.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){setAvailability(false,data.message||'Unable to check availability.');return}setAvailability(!!data.available,data.message)}
async function confirmBooking(){const err=document.getElementById('book-error'),ok=document.getElementById('book-success');err.style.display='none';ok.style.display='none';await checkAvailability();if(!selectedAvailable){err.textContent='Selected dates are unavailable.';err.style.display='block';return}const fd=new FormData();fd.append('action','book');fd.append('cottage_id',currentCottage.id);fd.append('guest_count',document.getElementById('booking-guest-count').value);fd.append('check_in',document.getElementById('checkin-date').value);fd.append('check_in_time',document.getElementById('checkin-time').value);fd.append('check_out',document.getElementById('checkout-date').value);fd.append('check_out_time',document.getElementById('checkout-time').value);const res=await fetch('reservations.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){err.textContent=data.message||'Booking failed.';err.style.display='block';return}ok.textContent=`Booking submitted. Booking ID: ${data.booking_id}. Down payment: ${money(data.down_payment)}.`;ok.style.display='block';await loadNotifications();showTab('bookings')}
async function fetchMyBookings(){try{const fd=new FormData();fd.append('action','my_bookings');const res=await fetch('reservations.php',{method:'POST',body:fd,cache:'no-store'});const data=await res.json();return data.success?data.bookings:[]}catch(e){console.error('Booking load failed',e);return[]}}
function formatDate(value){if(!value)return'N/A';const d=new Date(value);return d.toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'})}
function markViewed(){const keys=(JSON.parse(localStorage.getItem('paradise_viewed_notifications')||'[]'));const seen=new Set(keys);bookings.filter(b=>b.status==='confirmed'||b.status==='cancelled').forEach(b=>seen.add(`${b.booking_id}:${b.status}`));localStorage.setItem('paradise_viewed_notifications',JSON.stringify([...seen]))}
function renderNotifications(){const list=document.getElementById('notify-list'),counter=document.getElementById('notify-count');const viewed=new Set(JSON.parse(localStorage.getItem('paradise_viewed_notifications')||'[]'));const updates=bookings.filter(b=>b.status==='confirmed'||b.status==='cancelled');const unread=updates.filter(b=>!viewed.has(`${b.booking_id}:${b.status}`)).length;counter.textContent=unread;counter.classList.toggle('show',unread>0);if(!updates.length){list.innerHTML='<div class="empty" style="padding:18px 10px">No booking updates yet.</div>';return}list.innerHTML=updates.map(b=>`<div class="notify-item"><div class="notify-top"><div class="notify-title">${b.cottage_name}</div><span class="status ${b.status}">${b.status.charAt(0).toUpperCase()+b.status.slice(1)}</span></div><div class="notify-meta">Booking ID: ${b.booking_id}<br>Check-in: ${formatDate(b.check_in)} ${b.check_in_time||''}<br>Check-out: ${formatDate(b.check_out)} ${b.check_out_time||''}</div></div>`).join('')}
async function loadNotifications(){bookings=await fetchMyBookings();renderNotifications()}
function toggleNotifications(){const panel=document.getElementById('notify-panel'),open=!panel.classList.contains('active');panel.classList.toggle('active');if(open){markViewed();renderNotifications()}}
async function loadMyBookings(){const container=document.getElementById('bookings-container');container.innerHTML='<div class="empty">Loading bookings...</div>';bookings=await fetchMyBookings();renderNotifications();if(!bookings.length){container.innerHTML='<div class="empty">No bookings yet.</div>';return}container.innerHTML=bookings.map(b=>`<div class="booking-card"><div class="booking-head" style="--booking-bg:url('${(b.image_url||'assets/cottages/paradise-nook-cottage.jpg').replace(/'/g,"%27")}')"><div><h3 style="font-family:Playfair Display,serif;font-size:1.15rem">${b.cottage_name}</h3><small>Booking ID: ${b.booking_id}</small></div><span class="status ${b.status}">${b.status.charAt(0).toUpperCase()+b.status.slice(1)}</span></div><div class="booking-body" style="--booking-bg:url('${(b.image_url||'assets/cottages/paradise-nook-cottage.jpg').replace(/'/g,"%27")}')"><div class="booking-list"><div class="booking-line"><div><strong>Guest</strong><span>${b.display_guest_name||profile?.full_name||'Customer'}</span></div></div><div class="booking-line"><div><strong>Check-In</strong><span>${formatDate(b.check_in)} ${b.check_in_time||''}</span></div></div><div class="booking-line"><div><strong>Check-Out</strong><span>${formatDate(b.check_out)} ${b.check_out_time||''}</span></div></div><div class="booking-line"><div><strong>Guests</strong><span>${b.guest_count||1}</span></div></div></div><div class="summary"><div class="big">${money(b.total_amount)}</div><div class="small">Down payment: ${money(b.down_payment||0)}<br>Cottage Type: ${b.cottage_type}<br>Booked on: ${formatDate(b.booked_on||b.created_at)}</div>${b.status!=='cancelled'?`<button class="cancel-btn" type="button" onclick="cancelBooking('${b.booking_id}')">Cancel Booking</button>`:''}</div></div></div>`).join('')}
async function cancelBooking(id){if(!confirm('Cancel this booking?'))return;const fd=new FormData();fd.append('action','cancel');fd.append('booking_id',id);const res=await fetch('reservations.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){alert(data.message||'Could not cancel booking.');return}await loadNotifications();loadMyBookings()}
async function logout(){const fd=new FormData();fd.append('action','logout');await fetch('auth.php',{method:'POST',body:fd});window.location.href='index.php'}
document.querySelectorAll('.overlay').forEach(el=>el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('active')}));document.addEventListener('click',e=>{const wrap=document.querySelector('.notify-wrap');if(wrap&&!wrap.contains(e.target))document.getElementById('notify-panel').classList.remove('active')});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.overlay.active').forEach(el=>el.classList.remove('active'))})
document.addEventListener('input',e=>{if(e.target&&e.target.id==='cottage-search')renderCottages()});
['booking-guest-count','checkin-date','checkin-time','checkout-date','checkout-time'].forEach(id=>document.addEventListener('change',e=>{if(e.target&&e.target.id===id){if(id==='checkin-date'){const v=document.getElementById('checkin-date').value;if(v){const next=new Date(v);next.setDate(next.getDate()+1);document.getElementById('checkout-date').min=next.toISOString().split('T')[0];if(document.getElementById('checkout-date').value<=v){document.getElementById('checkout-date').value=next.toISOString().split('T')[0]}}}updateBookingSummary();checkAvailability()}}));
async function boot(){await loadCottages();await loadProfile();await loadNotifications();refreshTimer=setInterval(()=>{loadNotifications()},10000)} boot();
</script>
</body>
</html>
