<?php
require_once __DIR__ . '/config.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: Thu, 01 Jan 1970 00:00:00 GMT');
$gcashQrAsset = htmlspecialchars(getPaymentQrAsset(), ENT_QUOTES, 'UTF-8');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Paradise Resort & Cottages</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
<style>
  :root{--teal:#009688;--teal-dark:#00796B;--bg:#eff8f7;--text:#173636;--muted:#698080;--shadow:0 18px 45px rgba(0,0,0,.12)}
  *{box-sizing:border-box;margin:0;padding:0} html{scroll-behavior:smooth} body{font-family:'Lato',sans-serif;background:var(--bg);color:var(--text)}
  nav{position:fixed;inset:0 0 auto 0;height:70px;padding:0 28px;background:rgba(0,121,107,.92);backdrop-filter:blur(12px);display:flex;align-items:center;justify-content:space-between;z-index:100}
  .brand{color:#fff;text-decoration:none;font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:700}
  .nav-links{display:flex;align-items:center;gap:14px}.nav-links a{color:#fff;text-decoration:none;font-weight:700;font-size:.9rem}
  .btn{border:none;border-radius:999px;padding:11px 18px;font-weight:700;cursor:pointer}.ghost{background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.35);color:#fff}.primary{background:#fff;color:var(--teal-dark)}
  .hero{width:100%;min-height:100vh;margin:0;padding:120px 24px 88px;display:grid;place-items:center;background-color:#0f6d69;background-image:linear-gradient(135deg,rgba(0,77,64,.58),rgba(0,150,136,.34)),var(--hero-image);background-size:cover,cover;background-repeat:no-repeat,no-repeat;background-position:center center,center center;transition:background-image .8s ease}
  .hero-wrap{width:min(1100px,100%);max-width:980px;display:grid;grid-template-columns:1fr;gap:0;align-items:center;justify-items:center;text-align:center}
  .hero h1{font-family:'Playfair Display',serif;color:#fff;font-size:clamp(3rem,7vw,5.4rem);line-height:1.05;margin-bottom:18px;text-shadow:0 10px 26px rgba(0,0,0,.24)}.hero p{color:rgba(255,255,255,.95);max-width:820px;line-height:1.65;margin-bottom:30px;font-size:clamp(1.02rem,1.8vw,1.16rem)}
  .hero-actions{display:flex;gap:14px;flex-wrap:wrap;justify-content:center}
  .dots{display:flex;gap:10px;margin-top:18px}.dot{width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,.35)}.dot.active{background:#fff}
  section:not(.hero){width:min(1180px,calc(100% - 34px));margin:0 auto;padding:72px 0}.title{text-align:center;margin-bottom:38px}.title h2{font-family:'Playfair Display',serif;font-size:2.35rem;color:var(--teal-dark);margin-bottom:8px}.title p{color:var(--muted);max-width:760px;margin:0 auto;line-height:1.6}
  .features{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}.feature{background:#fff;border-radius:22px;padding:26px;box-shadow:var(--shadow);text-align:center}.feature b{display:inline-flex;width:58px;height:58px;border-radius:18px;background:#e6f6f4;align-items:center;justify-content:center;color:var(--teal-dark);margin-bottom:14px}
  .cottages{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:24px}.card{background:#fff;border-radius:24px;overflow:hidden;box-shadow:var(--shadow);transition:transform .25s}.card:hover{transform:translateY(-8px)}.media{position:relative;height:220px}.media img{width:100%;height:100%;object-fit:cover}.hover{position:absolute;inset:0;padding:18px;background:linear-gradient(180deg,rgba(8,24,24,.08),rgba(8,24,24,.84));color:#fff;opacity:0;transition:opacity .25s;display:flex;flex-direction:column;justify-content:flex-end}.card:hover .hover{opacity:1}
  .hover p{font-size:.84rem;line-height:1.5;margin:8px 0 12px}.badges{display:flex;flex-wrap:wrap;gap:8px}.badges span{padding:6px 10px;border-radius:999px;background:rgba(255,255,255,.16);font-size:.74rem}
  .info{padding:18px 20px 20px}.info h3{font-family:'Playfair Display',serif;font-size:1.24rem;margin-bottom:8px}.info p{color:var(--muted);line-height:1.55;min-height:48px}.meta{display:flex;gap:12px;flex-wrap:wrap;font-size:.84rem;color:#5a7272;margin:12px 0}.pill{background:#e8f6f4;color:var(--teal-dark);padding:5px 10px;border-radius:999px;font-weight:700}
  .bottom{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-top:12px}.rate{font-size:1.35rem;font-weight:700;color:var(--teal-dark)}.rate small{font-size:.78rem;color:#869999}.book-btn{background:var(--teal);color:#fff}
  .contact-wrap{background:linear-gradient(180deg,#28bec6,#1caeb6);padding:44px 18px}.contact{width:min(1180px,100%);margin:0 auto;background:#d9f6f7;border-radius:28px;padding:28px 34px 24px;box-shadow:var(--shadow)}.contact h2{font-family:'Playfair Display',serif;text-align:center;font-size:2rem;margin-bottom:18px}.contact-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;text-align:center}.contact-grid strong{display:block;margin-bottom:8px}.contact-grid p{color:#385252;line-height:1.6}
  footer{background:#143f42;color:#fff;text-align:center;padding:18px 16px 64px}.footer-title{font-family:'Playfair Display',serif;font-size:1.15rem;margin-bottom:6px}.footer-sub{font-size:.82rem;color:rgba(255,255,255,.88)}
  .overlay{position:fixed;inset:0;background:rgba(8,22,22,.62);display:none;align-items:center;justify-content:center;z-index:200;padding:20px}.overlay.active{display:flex}
  .modal{width:min(100%,540px);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;box-shadow:0 24px 60px rgba(0,0,0,.22);padding:28px;position:relative}.wide{width:min(100%,780px)}.close{position:absolute;top:12px;right:16px;background:none;border:none;font-size:1.7rem;color:#9aa9a9;cursor:pointer}
  .modal h2{font-family:'Playfair Display',serif;font-size:1.7rem;color:var(--teal-dark);margin-bottom:6px}.sub{color:var(--muted);line-height:1.55;margin-bottom:20px}
  .grid{display:grid;gap:14px}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.group label{display:block;font-size:.82rem;font-weight:700;color:#4e6666;margin-bottom:6px}.group input,.group select{width:100%;padding:12px 14px;border:1.5px solid #d8e8e7;border-radius:16px;background:#fbfefe;font-size:.94rem;outline:none}
  .layout{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.side{background:linear-gradient(180deg,rgba(0,150,136,.08),rgba(77,182,172,.03));border:1px solid rgba(0,150,136,.12);border-radius:22px;padding:18px}.box,.qr{background:#fff;border:1px solid #e7f1f0;border-radius:18px;padding:16px;margin-bottom:14px}.value{font-size:1.45rem;font-weight:700;color:var(--teal-dark)}.note{font-size:.82rem;color:#6d8484;line-height:1.6;margin-top:6px}
  .qr{text-align:center}.qr img{width:min(100%,260px);max-height:420px;height:auto;object-fit:contain;margin:0 auto 12px;display:block}.avail{display:inline-flex;padding:10px 14px;border-radius:999px;font-size:.82rem;font-weight:700;background:#edf8f7;color:var(--teal-dark);margin:6px 0 14px}.avail.available{background:#e8f5e9;color:#2e7d32}.avail.unavailable{background:#ffebee;color:#c62828}
  .actions{display:flex;justify-content:flex-end;gap:12px;margin-top:18px}.secondary{background:#f2f6f6;color:#617777}.error,.success{display:none;margin-top:12px;font-size:.84rem;font-weight:700;text-align:center}.error{color:#c62828}.success{color:#2e7d32}
  @media(max-width:1024px){.layout,.features,.contact-grid{grid-template-columns:1fr}.hero{padding:110px 24px 84px;background-size:cover,cover}.hero-wrap{max-width:760px}} @media(max-width:760px){nav{padding:0 18px}.nav-links a:not(.btn){display:none}.grid.two{grid-template-columns:1fr}.bottom{flex-direction:column;align-items:flex-start}.hero{min-height:88vh;padding:104px 18px 70px;background-size:cover,cover}.hero-wrap{max-width:100%}.hero h1{font-size:clamp(2.5rem,11vw,4rem)}}
</style>
</head>
<body>
<nav>
  <a class="brand" href="index.php">Paradise Resort & Cottages</a>
  <div class="nav-links">
    <a href="#" onclick="openModal('register');return false;">Create Account</a>
    <a href="#amenities">Amenities</a>
    <a href="#contact">Visit Us</a>
    <button class="btn ghost" type="button" onclick="openModal('login')">Sign In</button>
    <button class="btn primary" type="button" onclick="openGuestModal()">Book Now</button>
  </div>
</nav>
<section class="hero" id="hero">
  <div class="hero-wrap">
    <div>
      <h1>Paradise Resort & Cottages</h1>
      <p>Experience the pinnacle of luxury and relaxation at our oceanside cottages.</p>
      <div class="hero-actions">
        <button class="btn primary" type="button" onclick="openGuestModal()">Book Your Stay</button>
        <button class="btn ghost" type="button" onclick="openModal('register')">Create Account</button>
      </div>
      <div class="dots" id="dots"></div>
    </div>
  </div>
</section>
<section id="amenities">
  <div class="title"><h2>Welcome to Paradise</h2><p>Browse the cottages below, hover each card to preview details, then book directly as a guest or sign in for account-based booking.</p></div>
  <div class="features">
    <div class="feature"><b>WF</b><h3>Fast WiFi</h3><p>Reliable internet in selected cottages and common areas.</p></div>
    <div class="feature"><b>AC</b><h3>Cool Comfort</h3><p>Air-conditioned rooms and breezy cottage layouts.</p></div>
    <div class="feature"><b>GR</b><h3>Group Ready</h3><p>Family spaces, barkada cottages, and event-ready options.</p></div>
    <div class="feature"><b>24</b><h3>Quick Support</h3><p>Simple reservation flow with guest and walk-in support.</p></div>
  </div>
</section>
<section id="cottages">
  <div class="title"><h2>Our Cottages</h2><p>Hover any cottage to view details, then book it right away.</p></div>
  <div class="cottages" id="cottages-container"><div style="grid-column:1/-1;text-align:center;color:#7d9292;padding:40px 10px">Loading cottages...</div></div>
</section>
<div class="contact-wrap" id="contact"><div class="contact"><h2>Visit Us</h2><div class="contact-grid"><div><strong>Location</strong><p>123 Paradise Beach Road<br>Tropical Island, TI 12345</p></div><div><strong>Hotline</strong><p>+63 912 345 6789<br>Available daily for resort and walk-in inquiries</p></div><div><strong>Email</strong><p>info@paradiseresort.com<br>reservations@paradiseresort.com</p></div></div></div></div>
<footer><div class="footer-title">&copy; 2026 Paradise Resort & Cottages. All rights reserved.</div><div class="footer-sub">Your tropical escape awaits.</div></footer>

<div class="overlay" id="login-modal"><div class="modal"><button class="close" type="button" onclick="closeModal('login')">&times;</button><h2>Welcome Back</h2><p class="sub">Sign in if you already have an account. Guest booking is also available from the homepage.</p><div class="grid"><div class="group"><label>Email</label><input type="email" id="login-email" placeholder="you@example.com"></div><div class="group"><label>Password</label><input type="password" id="login-password" placeholder="Password"></div></div><div class="error" id="login-error"></div><div class="actions"><button class="btn secondary" type="button" onclick="closeModal('login')">Cancel</button><button class="btn primary" type="button" onclick="doLogin()">Sign In</button></div></div></div>
<div class="overlay" id="register-modal"><div class="modal"><button class="close" type="button" onclick="closeModal('register')">&times;</button><h2>Create Your Account</h2><p class="sub">Make repeat bookings faster and manage your details later from the customer page.</p><div class="grid two"><div class="group"><label>Full Name</label><input type="text" id="reg-name" placeholder="Juan Dela Cruz"></div><div class="group"><label>Phone Number</label><input type="text" id="reg-phone" placeholder="09XXXXXXXXX"></div><div class="group"><label>Email</label><input type="email" id="reg-email" placeholder="you@example.com"></div><div class="group"><label>Password</label><input type="password" id="reg-password" placeholder="Minimum 6 characters"></div><div class="group" style="grid-column:1/-1"><label>Confirm Password</label><input type="password" id="reg-confirm" placeholder="Repeat password"></div></div><div class="error" id="register-error"></div><div class="success" id="register-success"></div><div class="actions"><button class="btn secondary" type="button" onclick="closeModal('register')">Cancel</button><button class="btn primary" type="button" onclick="doRegister()">Create Account</button></div></div></div>
<div class="overlay" id="guest-modal"><div class="modal wide"><button class="close" type="button" onclick="closeModal('guest')">&times;</button><h2>Book as Guest</h2><p class="sub">No account required. Choose your cottage, dates, times, and guest count, then use the GCash QR for the down payment reference.</p><div class="layout"><div><div class="grid two"><div class="group" style="grid-column:1/-1"><label>Cottage</label><select id="guest-cottage"></select></div><div class="group"><label>Full Name</label><input type="text" id="guest-name" placeholder="Guest name"></div><div class="group"><label>Phone Number</label><input type="text" id="guest-phone" placeholder="09XXXXXXXXX"></div><div class="group"><label>Email</label><input type="email" id="guest-email" placeholder="Optional"></div><div class="group"><label>Number of Guests</label><input type="number" min="1" id="guest-count" value="1"></div><div class="group"><label>Check-In Date</label><input type="date" id="guest-checkin-date"></div><div class="group"><label>Check-In Time</label><input type="time" id="guest-checkin-time" value="14:00"></div><div class="group"><label>Check-Out Date</label><input type="date" id="guest-checkout-date"></div><div class="group"><label>Check-Out Time</label><input type="time" id="guest-checkout-time" value="12:00"></div></div><div class="avail" id="guest-availability">Select dates to check availability.</div><div class="error" id="guest-book-error"></div><div class="success" id="guest-book-success"></div><div class="actions"><button class="btn secondary" type="button" onclick="closeModal('guest')">Cancel</button><button class="btn primary" id="guest-book-btn" type="button" onclick="submitGuestBooking()">Confirm Guest Booking</button></div></div><div class="side"><div class="box"><div style="font-size:.84rem;color:#6d8484;margin-bottom:6px">Total Amount</div><div class="value" id="guest-total">PHP 0</div><div class="note" id="guest-total-meta">Choose a cottage and stay dates to compute the total.</div></div><div class="box"><div style="font-size:.84rem;color:#6d8484;margin-bottom:6px">Required Down Payment</div><div class="value" id="guest-down-payment">PHP 0</div><div class="note">Guest bookings show a 30% down payment reference for staff verification.</div></div><div class="qr"><img src="<?= $gcashQrAsset ?>" alt="GCash QR"><strong style="display:block;color:var(--teal-dark);margin-bottom:6px">GCash QR</strong><div class="note">Scan after placing the reservation. The down payment amount is saved with your booking details.</div></div></div></div></div></div>

<script>
let cottages=[],heroIndex=0,heroTimer=null,guestAvailable=false;
async function fetchJson(url, options={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(url,{cache:'no-store',...options,signal:controller.signal});const text=await res.text();return JSON.parse(text)}finally{clearTimeout(timeout)}}
function openModal(type){document.getElementById(type+'-modal').classList.add('active')}
function closeModal(type){document.getElementById(type+'-modal').classList.remove('active')}
function money(v){return 'PHP '+Number(v||0).toLocaleString()}
function selectedCottage(){const id=Number(document.getElementById('guest-cottage').value);return cottages.find(c=>Number(c.id)===id)||null}
function setAvailability(ok,msg){const el=document.getElementById('guest-availability');const btn=document.getElementById('guest-book-btn');guestAvailable=ok;el.textContent=msg;el.className='avail'+(msg?(' '+(ok?'available':'unavailable')):'');btn.disabled=!ok}
function fillCottageOptions(preId=null){const select=document.getElementById('guest-cottage');const target=preId||Number(select.value)||(cottages[0]?Number(cottages[0].id):0);select.innerHTML=cottages.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(target)?'selected':''}>${c.name} - ${money(c.price)} / ${c.pricing_unit}</option>`).join('')}
function updateDots(){document.getElementById('dots').innerHTML=cottages.slice(0,5).map((_,i)=>`<span class="dot ${i===heroIndex?'active':''}"></span>`).join('')}
function showSlide(i){if(!cottages.length)return;heroIndex=i%cottages.length;document.getElementById('hero').style.setProperty('--hero-image',`url('${(cottages[heroIndex].image_url||'').replace(/'/g,"%27")}')`);updateDots()}
function startSlider(){if(heroTimer)clearInterval(heroTimer);if(!cottages.length)return;showSlide(0);heroTimer=setInterval(()=>showSlide((heroIndex+1)%cottages.length),4200)}
function initDates(){const now=new Date(),tom=new Date(now);tom.setDate(tom.getDate()+1);const d1=now.toISOString().split('T')[0],d2=tom.toISOString().split('T')[0];const inEl=document.getElementById('guest-checkin-date'),outEl=document.getElementById('guest-checkout-date');inEl.min=d1;outEl.min=d2;if(!inEl.value)inEl.value=d1;if(!outEl.value)outEl.value=d2}
function updateGuestSummary(){const c=selectedCottage(),total=document.getElementById('guest-total'),down=document.getElementById('guest-down-payment'),meta=document.getElementById('guest-total-meta');if(!c){total.textContent='PHP 0';down.textContent='PHP 0';meta.textContent='Choose a cottage and stay dates to compute the total.';return}const start=new Date(document.getElementById('guest-checkin-date').value),end=new Date(document.getElementById('guest-checkout-date').value);let units=Math.max(1,Math.round((end-start)/86400000));if(c.pricing_unit==='event')units=1;const grand=Number(c.price)*units;total.textContent=money(grand);down.textContent=money(grand*.3);meta.textContent=`${units} ${c.pricing_unit}${units===1?'':'s'} x ${money(c.price)} | Capacity ${c.capacity} guests`}
async function checkGuestAvailability(){const c=selectedCottage();if(!c){setAvailability(false,'Please choose a cottage first.');return}setAvailability(false,'Checking availability...');const fd=new FormData();fd.append('action','availability');fd.append('cottage_id',c.id);fd.append('check_in',document.getElementById('guest-checkin-date').value);fd.append('check_out',document.getElementById('guest-checkout-date').value);fd.append('guest_count',document.getElementById('guest-count').value);const res=await fetch('reservations.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){setAvailability(false,data.message||'Unable to check availability.');return}setAvailability(!!data.available,data.message)}
function openGuestModal(cottageId=null){fillCottageOptions(cottageId);initDates();document.getElementById('guest-book-error').style.display='none';document.getElementById('guest-book-success').style.display='none';updateGuestSummary();checkGuestAvailability();openModal('guest')}
async function submitGuestBooking(){const err=document.getElementById('guest-book-error'),ok=document.getElementById('guest-book-success');err.style.display='none';ok.style.display='none';await checkGuestAvailability();if(!guestAvailable){err.textContent='Selected dates are unavailable for this cottage.';err.style.display='block';return}const c=selectedCottage();const fd=new FormData();fd.append('action','book_guest');fd.append('cottage_id',c.id);fd.append('guest_name',document.getElementById('guest-name').value);fd.append('guest_phone',document.getElementById('guest-phone').value);fd.append('guest_email',document.getElementById('guest-email').value);fd.append('guest_count',document.getElementById('guest-count').value);fd.append('check_in',document.getElementById('guest-checkin-date').value);fd.append('check_in_time',document.getElementById('guest-checkin-time').value);fd.append('check_out',document.getElementById('guest-checkout-date').value);fd.append('check_out_time',document.getElementById('guest-checkout-time').value);const res=await fetch('reservations.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){err.textContent=data.message||'Guest booking failed.';err.style.display='block';return}ok.textContent=`${data.message} Booking ID: ${data.booking_id}. Down payment: ${money(data.down_payment)}.`;ok.style.display='block'}
async function doLogin(){const err=document.getElementById('login-error');err.style.display='none';const fd=new FormData();fd.append('action','login');fd.append('email',document.getElementById('login-email').value);fd.append('password',document.getElementById('login-password').value);const res=await fetch('auth.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){err.textContent=data.message||'Login failed.';err.style.display='block';return}window.location.href=data.redirect}
async function doRegister(){const err=document.getElementById('register-error'),ok=document.getElementById('register-success');err.style.display='none';ok.style.display='none';const fd=new FormData();fd.append('action','register');fd.append('full_name',document.getElementById('reg-name').value);fd.append('phone',document.getElementById('reg-phone').value);fd.append('email',document.getElementById('reg-email').value);fd.append('password',document.getElementById('reg-password').value);fd.append('confirm_password',document.getElementById('reg-confirm').value);const res=await fetch('auth.php',{method:'POST',body:fd});const data=await res.json();if(!data.success){err.textContent=data.message||'Registration failed.';err.style.display='block';return}ok.textContent='Account created successfully. You can sign in now.';ok.style.display='block'}
function renderCottages(){const container=document.getElementById('cottages-container');if(!cottages.length){container.innerHTML='<div style="grid-column:1/-1;text-align:center;color:#7d9292;padding:40px 10px">No cottages available right now.</div>';return}container.innerHTML=cottages.map(c=>{const amenities=(c.amenities||'').split(',').map(v=>v.trim()).filter(Boolean);return `<article class="card"><div class="media"><img src="${c.image_url}" alt="${c.name}" onerror="this.src='assets/cottages/paradise-nook-cottage.jpg'"><div class="hover"><h4>${c.name}</h4><p>${c.description||'A tropical stay designed for comfort and easy resort access.'}</p><div class="badges"><span>${c.type}</span><span>${c.capacity} guests</span>${amenities.slice(0,3).map(item=>`<span>${item}</span>`).join('')}</div></div></div><div class="info"><h3>${c.name}</h3><p>${c.description||'A tropical stay designed for comfort and easy resort access.'}</p><div class="meta"><span class="pill">${c.type}</span><span>Capacity: <strong>${c.capacity}</strong></span></div><div class="bottom"><div class="rate">${money(c.price)} <small>/ ${c.pricing_unit}</small></div><button class="btn book-btn" type="button" onclick="openGuestModal(${c.id})">Book as Guest</button></div></div></article>`}).join('')}
async function loadCottages(){const container=document.getElementById('cottages-container');try{const data=await fetchJson('cottages.php?action=list');if(!data.success||!Array.isArray(data.cottages)){throw new Error(data.error||data.message||'Could not load cottages.')}cottages=data.cottages;renderCottages();fillCottageOptions();initDates();updateGuestSummary();checkGuestAvailability();startSlider()}catch(e){console.error('Homepage cottage load failed',e);container.innerHTML='<div style="grid-column:1/-1;text-align:center;color:#7d9292;padding:40px 10px">Could not load cottages. Please make sure MySQL is running.</div>'}}
['guest-cottage','guest-count','guest-checkin-date','guest-checkout-date','guest-checkin-time','guest-checkout-time'].forEach(id=>document.addEventListener('change',e=>{if(e.target&&e.target.id===id){if(id==='guest-checkin-date'){const v=document.getElementById('guest-checkin-date').value;if(v){const next=new Date(v);next.setDate(next.getDate()+1);document.getElementById('guest-checkout-date').min=next.toISOString().split('T')[0];if(document.getElementById('guest-checkout-date').value<=v){document.getElementById('guest-checkout-date').value=next.toISOString().split('T')[0]}}}updateGuestSummary();checkGuestAvailability()}}))
document.querySelectorAll('.overlay').forEach(el=>el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('active')}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.overlay.active').forEach(el=>el.classList.remove('active'))})
loadCottages();
</script>
</body>
</html>
